title: 👹 OGRE: (E)arth Observation and Generative models for Rare Events detection
description: (E)arth Observation and Generative models for Rare Events detection (OGRE, ANR-25-ASTR-0012, 2026-2029) is a research project funded by the Agence Nationale de la Recherche (ANR) under the ASTRID program with a grant from “Agence Innovation Défense” (AID).

